enabled_features:
  - autolabeler
  - bot-pr-merge
  - stalebot
  - merge-queue
  - pr-template-validator
  - stale-branch-bot
  - bot-admin-merge
  - bot-translation-merge
merge_user: alexandreos
admin_users: [alexandreos]
